zbt: (control,zbtrc) [CRITICAL] ContourParams, toggle_hooks, etc.
- ContourParams class introduced as new dispatcher.
  - [CRITICAL] must be list (but why?).
  - colors=['black'] works, but colors='black' not. Strange.
- default annotated contour changed to the last one.
- fix and improve norm propagation.
  - [critical] fix TwoSlopeNorm vmin vmax initialization
  - reference range is introduced to check whether colormap is changed
  - sym Norm introduced.
- turn_* command introduced.
- mouse scroll event introduced.
  - Stepping is limited to one (to be improved later).
- [CRITICAL] toggle_hooks introduced.
  - canvas is stored and restored to avoid updating when savefig() is
    called.  Otherwise error raised at copy_from_bbox such as:
    AttributeError: 'FigureCanvasPS' object has no attribute 'copy_from_bbox'